"use client";

import React from "react";
import {IUserData} from "@/app/_models/user";
import Head from "next/head";
import Headline from "../modules/profile/Headline";

interface IMainProps {
    profileMain: IUserData;
}

export const MainPage: React.FC<IMainProps> = ({profileMain}) => {

    const styles = {
        mainContainer: `m-auto w-2/3 mt-24`
    }

    return (
        <>
            <Head>
                <title>Portfolio - {profileMain["profile"]["name"]}</title>
                <meta name="Description" content="Generated by create next app"/>
            </Head>
            <main className={styles.mainContainer}>
                <article id="mainContainer" className={``}>
                    <Headline headLine={profileMain["profile"]}/>
                </article>
            </main>
        </>
    );
};

export default MainPage;
