"use client"

import Head from 'next/head'
import Headline from '../../default/features/DevProfile/components/Headline'
import AboutMe from '../../default/features/DevProfile/components/AboutMe'
import Experience from '../../default/features/DevProfile/components/Experience'
import FeaturedProject from '../../default/features/DevProfile/components/FeaturedProject'
import OtherProjects from '../../default/features/DevProfile/components/OtherProjects'
import ContactMe from '../../default/features/DevProfile/components/ContactMe'
import { IUserData } from '../../_models/user'
import { IStyles } from '../../default/common/MainClientPage'

interface IMainProps {
    profileMain: IUserData;
    styles?: IStyles;
}

export const Main: React.FC<IMainProps> = ({ profileMain, styles }) => {

    return (
        <>
            <Head>
                <title>Portfolio - {profileMain["profile"]["name"]}</title>
                <meta
                    name="description"
                    content="Generated by create next app" />
            </Head>
            <main className='m-auto w-2/3 mt-24' >
                <article
                    id="mainContainer"
                    className={``}
                >
                    <Headline
                        headLine={profileMain["profile"]}
                        styles={styles}
                    />
                    <AboutMe
                        aboutMe={profileMain["aboutMe"]}
                        styles={styles}
                    />
                    <Experience
                        jobExperience={profileMain["jobs"]}
                        styles={styles}
                    />
                    <FeaturedProject projectWorks={profileMain["projects"]} />
                    <OtherProjects projectWorks={profileMain["subprojects"]} />
                    <ContactMe contactInfo={profileMain["contactInfo"]} />
                </article>
            </main>
        </>
    )
}

export default Main;