"use client";

import React from "react";
import { IStyles } from "@/app/_models/styles";
import { IUserData } from "@/app/_models/user";
import Head from "next/head";
import Headline from "../modules/profile/Headline";

interface IMainProps {
  profileMain: IUserData;
  theme: IStyles;
}

export const Main: React.FC<IMainProps> = ({ profileMain, theme }) => {
  return (
    <>
      <Head>
        <title>Portfolio - {profileMain["profile"]["name"]}</title>
        <meta name="description" content="Generated by create next app" />
      </Head>
      <main className="m-auto w-2/3 mt-24">
        <article id="mainContainer" className={``}>
          <Headline headLine={profileMain["profile"]} theme={theme} />
        </article>
      </main>
    </>
  );
};

export default Main;
