import Head from 'next/head'
export default function Landing({ handleEntry }) {

    return (
        <>
            <Head>
                <title>Portfolio - Landing</title>
                <meta name="description" content="Generated by create next app" />
            </Head>
            <main>
                <h1>Landing Page</h1>
                <button onClick={handleEntry}>Enter</button>
            </main>
        </>
    )
}