import Head from 'next/head'
export default function Landing({ handleEntry }) {

    return (
        <>
            <Head>
                <title>Portfolio - Landing</title>
                <meta name="description" content="Generated by create next app" />
            </Head>
            <main id="landingMain">
                <h1 id="landingH1">Landing Page</h1>
                <button id="landingButton" onClick={handleEntry}>Enter</button>
            </main>
        </>
    )
}