import Head from 'next/head'
import Headline from './Bio/Headline'
import AboutMe from './Bio/AboutMe'
import Experience from './Bio/Experience'
import Work from './Bio/Work'
import ContactMe from './Bio/Contact'


export default function Main({ profileMain }) {

    return (
        <>
            <Head>
                <title>Portfolio - {profileMain["profile"]["name"]}</title>
                <meta
                    name="description"
                    content="Generated by create next app" />
            </Head>
            <main className='m-auto w-2/3' >
                <article
                    id="mainContainer">
                    <Headline headLine={profileMain["profile"]} />
                    <AboutMe aboutMe={profileMain["aboutMe"]} />
                    <Experience jobExperience={profileMain["jobs"]} />
                    <Work projectWorks={profileMain["projects"]} />
                    <ContactMe contactInfo={profileMain["contactInfo"]} />
                </article>
            </main>
        </>
    )
}