import Head from "next/head";

const Layout = ({ children }) => {
    return (
        <>
            <Head>
                <title>Portfolio - </title>
                <meta
                    name="description"
                    content="Generated by create next app" />
            </Head>
            <div className="min-h-screen">
                <main>
                    {children}
                </main>
            </div>
        </>
    )
}

export default Layout