"use client"

import { IUserData } from '@/models/user';
import Head from 'next/head'
import AboutMe from '../modules/profile/AboutMe';
import ContactMe from '../modules/profile/ContactMe';
import Experience from '../modules/profile/Experience';
import FeaturedProject from '../modules/profile/FeaturedProject';
import Headline from '../modules/profile/Headline';
import OtherProjects from '../modules/profile/OtherProjects';
import { IStyles } from './MainClientPage';


interface IMainProps {
    profileMain: IUserData;
    styles?: IStyles;
}

export const Main: React.FC<IMainProps> = ({ profileMain, styles }) => {

    return (
        <>
            <Head>
                <title>Portfolio - {profileMain["profile"]["name"]}</title>
                <meta
                    name="description"
                    content="Generated by create next app" />
            </Head>
            <main className='m-auto w-2/3 mt-24' >
                <article
                    id="mainContainer"
                    className={``}
                >
                    <Headline
                        headLine={profileMain["profile"]}
                        styles={styles}
                    />
                    <AboutMe
                        aboutMe={profileMain["aboutMe"]}
                        styles={styles}
                    />
                    <Experience
                        jobExperience={profileMain["jobs"]}
                        styles={styles}
                    />
                    <FeaturedProject projectWorks={profileMain["projects"]} />
                    <OtherProjects projectWorks={profileMain["subprojects"]} />
                    <ContactMe contactInfo={profileMain["contactInfo"]} />
                </article>
            </main>
        </>
    )
}

export default Main;